USE covid19;
#Q1- Extracting details of the patient's result, date and other basic information from 3 tables
SELECT T.TID, P.PID, CONCAT(P.P_FIRSTNAME, ' ', P.P_LASTNAME) AS FULLNAME
, T.RESULT, P.P_SYMPTOMS, T.SAMPLEDATE, P.P_ADMITDATE, H.H_NAME, H_STATE 
FROM TESTING T JOIN PATIENTS P JOIN HOSPITALS H
ON H.TID = T.TID AND H.PID = P.PID
ORDER BY P.PID;

#Q2- Query to see the result of the patient and the details of the hospital where the patient has been admitted
SELECT T.TID AS NUM, T.T_STATE, T.RESULT, H.H_NAME, H.H_CONTACT, H.ADDRESS, H.PID, H.CITY 
FROM TESTING T JOIN HOSPITALS H 
ON T.TID = H.TID 
GROUP BY T_STATE
ORDER BY H.CITY DESC;

#Q3- ratio of the number of cases in the affected areas
SELECT AID, A_STATE, (A_DEATHS/A_POSITIVE)*100 AS DEATH_RATE, (A_Positive/(A_Positive+A_NEGATIVE+A_Deaths))*100 AS POSITIVE_PERCENTAGE,
(A_NEGATIVE/(A_Deaths+A_Negative+A_POSITIVE))*100 AS NEGATIVE_PERCENTAGE, ROG_ZONE
FROM affectedareas
GROUP BY A_NAME
ORDER BY DEATH_RATE DESC;

#Q4- QUERY TO FIND THE ALLOTMENT OF STAFF TO PATIENTS FROM DIFF STATES
SELECT S.SID, S.S_TYPE, CONCAT(S.S_FIRSTNAME,' ', S.S_LASTNAME) AS STAFF_NAME, S.S_WARDNO
,CONCAT(P.P_FIRSTNAME,' ', P.P_LASTNAME) AS PATIENT_NAME, P.P_AGE, P.P_GENDER,P.P_ADMITDATE
, P.P_IMPROVEMENTDATE, P.P_NOTES AS SUMMARY, S.S_CONTACT AS STAFF_NUMBER,P.P_NATIONALITY
FROM STAFF S JOIN STAFFHASPATS SP JOIN PATIENTS P
ON S.SID = SP.SID AND SP.PID = P.PID
WHERE S.S_TYPE = 'Doctor'
ORDER BY S.SID;

#Q5- QUERY TO SEE IN WHAT AREA THE PATIENT WAS AFFECTED AND HOW ADVERSELY THAT AREA HAS BEEN EFFECTED BY COVID-19
SELECT CONCAT(P.P_FIRSTNAME,' ',P.P_LASTNAME) AS FULLNAME, A.AID, P.P_DETECTEDAREA, A.ROG_ZONE, A.A_POSITIVE AS POSITIVES
,A.A_DEATHS AS DEATHS
FROM PATIENTS P JOIN AFFECTEDAREAS A 
ON P.AID = A.AID
ORDER BY POSITIVES DESC;

#Q6- QUERY TO FIND THE DETAILS OF PATIENTS BETWEEN AGES 60 AND 80 WITH NEGATIVE RESULTS FROM TESTING
SELECT CONCAT(P.P_FIRSTNAME,' ',P.P_LASTNAME) AS FULLNAME, P.P_AGE, P.P_NATIONALITY, P.P_TRAVELINFO
,P.P_Symptoms, T.SAMPLEDATE, T.RESULT
FROM PATIENTS P JOIN TESTING T
ON P.PID = T.PID
WHERE P.P_AGE BETWEEN 60 AND 80 AND T.RESULT='N'
ORDER BY P.PID DESC;

#RAMOJI'S QUERIES
SELECT  max(A_Positive) as 'Highest pos cases in red zone' from AFFECTEDAREAS Where RYG_ZONE = 'R';
SELECT * FROM AFFECTEDAREAS WHERE RYG_ZONE = 'O' AND A_Positive > 400 ;
SELECT AVG(A_Deaths) FROM AFFECTEDAREAS WHERE A_State = 'Maharastra' ;
#Q7-
-- QUERY TO GET THE HIGHEST Positive cases and correponding state and city
select A_Name, A_STATE, A_Positive  
FROM AFFECTEDAREAS 
where A_Positive in (select max(A_Positive) from AFFECTEDAREAS );

#Q8- QUERY to see the effects of covid 19 who's age is more than 40
##
SELECT concat(P_FIRSTNAME,'',P_LastName) as 'Patient Details',P_Age,P_Symptoms, P_Notes 
FROM patients P 
where P_Age > '40';

#Q9- QUERY FOR patients sample THAT must be assigned to a laboratory 
--- 
SELECT concat( Patients.P_FIRSTNAME,'',Patients.P_LASTNAME)  as 'Individual'
, Testing.LabName, Testing.LabType, Testing.T_Address, Testing.T_State
FROM Patients
INNER JOIN Testing ON Patients.PID = Testing.PID order by Testing.T_State ;


#Q10
SELECT S.PID, P.P_FIRSTNAME,P.P_ADMITDATE, S.S_FIRSTNAME
FROM STAFF S JOIN PATIENTS P 
ON S.PID = P.PID; 


#Q7-
/*SELECT distinct S.PID, SP.PID, S.S_FIRSTNAME, SP.SID, S.SID
FROM STAFF S JOIN STAFFHASPATS SP 
ON S.PID = SP.PID
WHERE S.S_FIRSTNAME = 'Pooja'; 
*/